// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckedResponse) Reset() {
	*x = CheckedResponse{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckedResponse) ProtoMessage() {}

func (x *CheckedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckedResponse.ProtoReflect.Descriptor instead.
func (*CheckedResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CheckedResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CheckUserExistsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsByIdRequest) Reset() {
	*x = CheckUserExistsByIdRequest{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsByIdRequest) ProtoMessage() {}

func (x *CheckUserExistsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsByIdRequest.ProtoReflect.Descriptor instead.
func (*CheckUserExistsByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUserExistsByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUserIdRequest) Reset() {
	*x = GetByUserIdRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUserIdRequest) ProtoMessage() {}

func (x *GetByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UsersPublicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserPublicResponse  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersPublicResponse) Reset() {
	*x = UsersPublicResponse{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersPublicResponse) ProtoMessage() {}

func (x *UsersPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersPublicResponse.ProtoReflect.Descriptor instead.
func (*UsersPublicResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UsersPublicResponse) GetUsers() []*UserPublicResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedResponse) Reset() {
	*x = DeletedResponse{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedResponse) ProtoMessage() {}

func (x *DeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedResponse.ProtoReflect.Descriptor instead.
func (*DeletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*AddressResponse     `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressesResponse) Reset() {
	*x = AddressesResponse{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressesResponse) ProtoMessage() {}

func (x *AddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressesResponse.ProtoReflect.Descriptor instead.
func (*AddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *AddressesResponse) GetAddresses() []*AddressResponse {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Ward          string                 `protobuf:"bytes,5,opt,name=ward,proto3" json:"ward,omitempty"`
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	IsDefault     *bool                  `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *AddressResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddressResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *AddressResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AddressResponse) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddressResponse) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *AddressResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressResponse) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	Ward          string                 `protobuf:"bytes,4,opt,name=ward,proto3" json:"ward,omitempty"`
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	IsDefault     bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAddressRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateAddressRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *CreateAddressRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CreateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Ward          string                 `protobuf:"bytes,5,opt,name=ward,proto3" json:"ward,omitempty"`
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateAddressRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *UpdateAddressRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *UpdateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MeasurementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Chest         int32                  `protobuf:"varint,4,opt,name=chest,proto3" json:"chest,omitempty"`
	Waist         int32                  `protobuf:"varint,5,opt,name=waist,proto3" json:"waist,omitempty"`
	Butt          int32                  `protobuf:"varint,6,opt,name=butt,proto3" json:"butt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementResponse) Reset() {
	*x = MeasurementResponse{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementResponse) ProtoMessage() {}

func (x *MeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementResponse.ProtoReflect.Descriptor instead.
func (*MeasurementResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *MeasurementResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeasurementResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MeasurementResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *MeasurementResponse) GetChest() int32 {
	if x != nil {
		return x.Chest
	}
	return 0
}

func (x *MeasurementResponse) GetWaist() int32 {
	if x != nil {
		return x.Waist
	}
	return 0
}

func (x *MeasurementResponse) GetButt() int32 {
	if x != nil {
		return x.Butt
	}
	return 0
}

type UpdateMeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Chest         int32                  `protobuf:"varint,4,opt,name=chest,proto3" json:"chest,omitempty"`
	Waist         int32                  `protobuf:"varint,5,opt,name=waist,proto3" json:"waist,omitempty"`
	Butt          int32                  `protobuf:"varint,6,opt,name=butt,proto3" json:"butt,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeasurementRequest) Reset() {
	*x = UpdateMeasurementRequest{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeasurementRequest) ProtoMessage() {}

func (x *UpdateMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeasurementRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMeasurementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMeasurementRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateMeasurementRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateMeasurementRequest) GetChest() int32 {
	if x != nil {
		return x.Chest
	}
	return 0
}

func (x *UpdateMeasurementRequest) GetWaist() int32 {
	if x != nil {
		return x.Waist
	}
	return 0
}

func (x *UpdateMeasurementRequest) GetButt() int32 {
	if x != nil {
		return x.Butt
	}
	return 0
}

func (x *UpdateMeasurementRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Dob           string                 `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedResponse) Reset() {
	*x = UpdatedResponse{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedResponse) ProtoMessage() {}

func (x *UpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedResponse.ProtoReflect.Descriptor instead.
func (*UpdatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Dob           string                 `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *ProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ProfileResponse) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type UserPublicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Profile       *ProfileResponse       `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPublicResponse) Reset() {
	*x = UserPublicResponse{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPublicResponse) ProtoMessage() {}

func (x *UserPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPublicResponse.ProtoReflect.Descriptor instead.
func (*UserPublicResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserPublicResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPublicResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserPublicResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserPublicResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserPublicResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserPublicResponse) GetProfile() *ProfileResponse {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\")\n" +
	"\x0fCheckedResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\",\n" +
	"\x1aCheckUserExistsByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x12GetByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\x13UsersPublicResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.user.UserPublicResponseR\x05users\"\x1f\n" +
	"\rGetOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fDeletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x11AddressesResponse\x123\n" +
	"\taddresses\x18\x01 \x03(\v2\x15.user.AddressResponseR\taddresses\"\xdc\x01\n" +
	"\x0fAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04ward\x18\x05 \x01(\tR\x04ward\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\"\n" +
	"\n" +
	"is_default\x18\a \x01(\bH\x00R\tisDefault\x88\x01\x01B\r\n" +
	"\v_is_default\"\xd6\x01\n" +
	"\x14CreateAddressRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04ward\x18\x04 \x01(\tR\x04ward\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"\xe6\x01\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04ward\x18\x05 \x01(\tR\x04ward\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\"\x95\x01\n" +
	"\x13MeasurementResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05chest\x18\x04 \x01(\x05R\x05chest\x12\x14\n" +
	"\x05waist\x18\x05 \x01(\x05R\x05waist\x12\x12\n" +
	"\x04butt\x18\x06 \x01(\x05R\x04butt\"\xb3\x01\n" +
	"\x18UpdateMeasurementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05chest\x18\x04 \x01(\x05R\x05chest\x12\x14\n" +
	"\x05waist\x18\x05 \x01(\x05R\x05waist\x12\x12\n" +
	"\x04butt\x18\x06 \x01(\x05R\x04butt\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"\xa5\x01\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x10\n" +
	"\x03dob\x18\x05 \x01(\tR\x03dob\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"+\n" +
	"\x0fUpdatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\x0fProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x10\n" +
	"\x03dob\x18\x05 \x01(\tR\x03dob\"\xbc\x01\n" +
	"\x12UserPublicResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12/\n" +
	"\aprofile\x18\x06 \x01(\v2\x15.user.ProfileResponseR\aprofile2\x9e\x05\n" +
	"\vUserService\x12N\n" +
	"\x13CheckUserExistsById\x12 .user.CheckUserExistsByIdRequest\x1a\x15.user.CheckedResponse\x12B\n" +
	"\x11GetUserPublicById\x12\x13.user.GetOneRequest\x1a\x18.user.UserPublicResponse\x12E\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x18.user.UserPublicResponse\x12N\n" +
	"\x11UpdateMeasurement\x12\x1e.user.UpdateMeasurementRequest\x1a\x19.user.MeasurementResponse\x12M\n" +
	"\x16GetMeasurementByUserId\x12\x18.user.GetByUserIdRequest\x1a\x19.user.MeasurementResponse\x12I\n" +
	"\x14GetAddressesByUserId\x12\x18.user.GetByUserIdRequest\x1a\x17.user.AddressesResponse\x12B\n" +
	"\rCreateAddress\x12\x1a.user.CreateAddressRequest\x1a\x15.user.AddressResponse\x12B\n" +
	"\rUpdateAddress\x12\x1a.user.UpdateAddressRequest\x1a\x15.user.AddressResponse\x12B\n" +
	"\rDeleteAddress\x12\x1a.user.DeleteAddressRequest\x1a\x15.user.DeletedResponseB\x03Z\x01.b\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_user_proto_goTypes = []any{
	(*CheckedResponse)(nil),            // 0: user.CheckedResponse
	(*CheckUserExistsByIdRequest)(nil), // 1: user.CheckUserExistsByIdRequest
	(*GetByUserIdRequest)(nil),         // 2: user.GetByUserIdRequest
	(*UsersPublicResponse)(nil),        // 3: user.UsersPublicResponse
	(*GetOneRequest)(nil),              // 4: user.GetOneRequest
	(*DeletedResponse)(nil),            // 5: user.DeletedResponse
	(*DeleteAddressRequest)(nil),       // 6: user.DeleteAddressRequest
	(*AddressesResponse)(nil),          // 7: user.AddressesResponse
	(*AddressResponse)(nil),            // 8: user.AddressResponse
	(*CreateAddressRequest)(nil),       // 9: user.CreateAddressRequest
	(*UpdateAddressRequest)(nil),       // 10: user.UpdateAddressRequest
	(*MeasurementResponse)(nil),        // 11: user.MeasurementResponse
	(*UpdateMeasurementRequest)(nil),   // 12: user.UpdateMeasurementRequest
	(*UpdateProfileRequest)(nil),       // 13: user.UpdateProfileRequest
	(*UpdatedResponse)(nil),            // 14: user.UpdatedResponse
	(*ProfileResponse)(nil),            // 15: user.ProfileResponse
	(*UserPublicResponse)(nil),         // 16: user.UserPublicResponse
}
var file_proto_user_proto_depIdxs = []int32{
	16, // 0: user.UsersPublicResponse.users:type_name -> user.UserPublicResponse
	8,  // 1: user.AddressesResponse.addresses:type_name -> user.AddressResponse
	15, // 2: user.UserPublicResponse.profile:type_name -> user.ProfileResponse
	1,  // 3: user.UserService.CheckUserExistsById:input_type -> user.CheckUserExistsByIdRequest
	4,  // 4: user.UserService.GetUserPublicById:input_type -> user.GetOneRequest
	13, // 5: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	12, // 6: user.UserService.UpdateMeasurement:input_type -> user.UpdateMeasurementRequest
	2,  // 7: user.UserService.GetMeasurementByUserId:input_type -> user.GetByUserIdRequest
	2,  // 8: user.UserService.GetAddressesByUserId:input_type -> user.GetByUserIdRequest
	9,  // 9: user.UserService.CreateAddress:input_type -> user.CreateAddressRequest
	10, // 10: user.UserService.UpdateAddress:input_type -> user.UpdateAddressRequest
	6,  // 11: user.UserService.DeleteAddress:input_type -> user.DeleteAddressRequest
	0,  // 12: user.UserService.CheckUserExistsById:output_type -> user.CheckedResponse
	16, // 13: user.UserService.GetUserPublicById:output_type -> user.UserPublicResponse
	16, // 14: user.UserService.UpdateProfile:output_type -> user.UserPublicResponse
	11, // 15: user.UserService.UpdateMeasurement:output_type -> user.MeasurementResponse
	11, // 16: user.UserService.GetMeasurementByUserId:output_type -> user.MeasurementResponse
	7,  // 17: user.UserService.GetAddressesByUserId:output_type -> user.AddressesResponse
	8,  // 18: user.UserService.CreateAddress:output_type -> user.AddressResponse
	8,  // 19: user.UserService.UpdateAddress:output_type -> user.AddressResponse
	5,  // 20: user.UserService.DeleteAddress:output_type -> user.DeletedResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	file_proto_user_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
